#Ce fichier contiens la config de base du serveur---
Install: false
General:
    NbrOffreDefaut: 5
    NbrOffreMax: 25
    PrixOffre: 5000
    CaseLigneSuite: _br_
    Name: computercraft_api
    Version: 2.0
    ModuleShowUser: true
    LimitPerGET: 100
DataBase:
    dbAdress: 0.0.0.0
    dbName: dbname
    dbUser: dbuser
    dbPassword: dbpass
    dbPort: 3306
SMTP:
    Host: smtp.serveur.net
    Username: snmpuser
    Password: snmppass
    Protocol: ssl
    Port: 465
    From: mailsender
    Reply: mailtoreply
MaxLengthChamps:
    Nom: 50
    Description: 450
    Coo: 50
    Code: 50
    Pseudo: 50
    Email: 50
Module:
    EnderStorage: true
    WirelessRedstone: true