#Ce fichier contiens la config de base du serveur---
Install: false
General:
    max_offre: 25
    prix_offre: 5000
    offre_depart: 5
    case_ligne_suite: -br-
    name: computercraft_api
DataBase:
    dbAdress: 0.0.0.0
    dbName: dbname
    dbUser: dbuser
    dbPassword: dbpass
    dbPort: 3306
SMTP:
    Host: smtp.serveur.net
    Username: snmpuser
    Password: snmppass
    Protocol: ssl
    Port: 465
    From: mailsender
    Reply: mailtoreply
message_error:
    0: succes - pas de retour attendu
    1: succes - commande realiser
    10: erreur - privilege insufisant
    11: erreur - login incorrect
    12: erreur - login admin incorrect
    13: erreur - parametre manquant
    20: erreur - utilisateur existant
    21: erreur - mot de passe non identique
    22: erreur - mail invalide
    23: erreur - mot ne respecte pas les regles de securite
    30: erreur - pas de stock
    31: erreur - quantite inferieur ou egal a 0
    32: erreur - cette offre est a vous
    33: erreur - offre inactive ou invalide
    34: erreur - pas d adresse de livraison
    40: erreur - edition statut invalide
    41: erreur - solde insufisant
    42: erreur - limite offre atteint
    51: erreur - offre ne vous apartient pas
    52: erreur - le prix est incorrect
    53: erreur - le stock est incorrect
    60: succes - pas de transaction
    61: erreur - jeton inferieur a 0
    70: erreur - nom adresse inexistant
    71: erreur - nom adresse deja utiliser
    72: erreur - nom adresse utiliser pour le commerce
    73: erreur - nom adresse utiliser pour la reception
    74: erreur - changement type adresse impossible en cours d utilisation
    75: erreur - suppression adresse impossible en cours d utilisation
role:
    0: client
    1: banque-terminal
    2: banque-routeur
    10: super-admin
type:
    0: vide
    1: objet
    2: liquide
    3: gaz
    4: autre
livraison:
    0: vide
    1: auto-rout
    2: manu
type_adresse:
    0: inactive
    1: reception
    2: commerce
type_transaction:
    1: commande
    2: transfert
    3: depot
    4: retrait
    5: achat option
statut_transaction:
    1: transaction valider
    2: transfert valider
    3: depot valider
    4: retrait valider
    5: achat option valider
    11: transaction refuser
    12: transfert refuser
    14: retrait refuser
    15: achat option refuser
statut_echange:
    1: attente - commande effectuer validation vendeur en attente
    2: attente - echange accepter paiement en attente
    3: valider - echange accepter paiement valider
    4: pret - commande pret a envoyer
    5: livraison - commande en cours de livraison
    6: livraison - commande livrer
    7: terminer - terminer
    10: refuser - echange refuser par le vendeur
    11: refuser - echange accepter paiement refuser
    13: annuler - annuler par le client
    20: litige - non recu
    21: litige - non conforme
    22: litige - trop long
    23: litige - plus interesser
    24: litige - trop cher
    25: litige - resolu
motif_litige:
    1: non recu
    2: non conforme
    3: trop long
    4: plus interesser
    5: trop cher