#Ce fichier contiens la config de base du serveur---
General:
    max_offre: 25
    prix_offre: 5000
    max_abo: 3
    prix_abo: 15000
    max_emprunt: 100000
message_error:
    0: succes - commande realiser
    1: danger - commande executer mais pas de retour
    2: erreur - privilege insufisant
    3: erreur - login incorrect
    4: erreur - parametre manquant
    5: erreur - utilisateur existant
    6: erreur - pas switch transaction
    10: erreur - limite offre atteint
    11: erreur - edition status incorrect
    12: erreur - offre inactive ou invalide
    13: erreur - pas de fond
    14: erreur - plafond prêt atteint
    15: erreur - pas de stock
    20: erreur -
    21: erreur - le prix est incorrect
    22: erreur - le stock est incorrect
role:
    banque: banque
    commerce: commerce
DataBase:
    dbAdress: 172.18.0.11
    dbName: minecraft_site
    dbUser: minecraft_site
    dbPassword: mc29md20mk12
    dbPort: 3306
statuts_echange:
    1: validation vendeur en attente
    2: echange accepter paiement en attente
    3: echange accepter paiement valider
    4: echange pret
    5: livraison en cours
    6: terminer
    10: echange refuser
    11: echange accepter paiement refuser