<?php
// get groupes/{id_utilisateur}/user
// get groupes/{id_utilisateur}/keyapi
// get groupes/{id_offre}/user
// get groupes/{id_offre}/keyapi
// get groupes/{id_adresse}/user
// get groupes/{id_adresse}/keyapi
// get groupes/{id_compte}/user
// get groupes/{id_compte}/keyapi
// get groupes/{id_keyapi}/user
// get groupes/{id_keyapi}/keyapi
// get groupes/{id_joueur}/user
// get groupes/{id_joueur}/keyapi
// get groupe/{id}
// set groupe/{id}/offre/{id}/add
// set groupe/{id}/offre/{id}/delete
// set groupe/{id}/adresse/{id}/add
// set groupe/{id}/adresse/{id}/delete
// set groupe/{id}/compte/{id}/add
// set groupe/{id}/compte/{id}/delete
// set groupe/{id}/keyapi/{id}/add
// set groupe/{id}/keyapi/{id}/delete
// set groupe/{id}/joueur/{id}/add
// set groupe/{id}/joueur/{id}/delete
// set groupe/{id}/nom
// set groupe/{id}/delete
// set groupe/{id}/droits/{id}/add
// set groupe/{id}/droits/{id}/delete
// set groupe/add

