<?php
// get offresactives
// get offresall
// get offres/{id_utilisateur}
// get offres/{id_compte}
// get offres/{id_adresse}
// get offres/{id_groupe}
// get offre/{id}
// set offre/{id}/compte
// set offre/{id}/adresse
// set offre/{id}/livraison
// set offre/{id}/prix
// set offre/{id}/description
// set offre/{id}/nom
// set offre/{id}/stock
// set offre/{id}/delete
// set offre/{id}/groupe/{id}/add
// set offre/{id}/groupe/{id}/delete
// set offre/add