#Ce fichier contiens la config de base du serveur---
Install: false
General:
    max_offre: 25
    prix_offre: 5000
    offre_depart: 5
    case_ligne_suite: _br_
    name: computercraft_api
    version: 2.0
DataBase:
    dbAdress: 0.0.0.0
    dbName: dbname
    dbUser: dbuser
    dbPassword: dbpass
    dbPort: 3306
SMTP:
    Host: smtp.serveur.net
    Username: snmpuser
    Password: snmppass
    Protocol: ssl
    Port: 465
    From: mailsender
    Reply: mailtoreply
message_error:
    0: succes - pas de retour attendu
    1: succes - commande realiser
    10: erreur - privilege insufisant
    11: erreur - login incorrect
    12: erreur - login admin incorrect
    13: erreur - parametre manquant
    20: erreur - utilisateur existant
    21: erreur - mot de passe non identique
    22: erreur - mail invalide
    23: erreur - mot ne respecte pas les regles de securite
    30: erreur - pas de stock
    31: erreur - quantite inferieur ou egal a 0
    32: erreur - cette offre est a vous
    33: erreur - offre inactive ou invalide
    34: erreur - pas d adresse de livraison
    40: erreur - edition statut invalide
    41: erreur - solde insufisant
    42: erreur - limite offre atteint
    51: erreur - offre ne vous apartient pas
    52: erreur - le prix est incorrect
    53: erreur - le stock est incorrect
    60: succes - pas de transaction
    61: erreur - jeton inferieur a 0
    70: erreur - nom adresse inexistant
    71: erreur - nom adresse deja utiliser
    72: erreur - nom adresse utiliser pour le commerce
    73: erreur - nom adresse utiliser pour la reception
    74: erreur - changement type adresse impossible en cours d utilisation
    75: erreur - suppression adresse impossible en cours d utilisation