function page_plus_info_client()
    table.insert(global_term_objet_write,{x = 1, y = 5, text = "id         :", back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 1, y = 6, text = "vendeur    :", back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 1, y = 7, text = "nom        :", back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 1, y = 8, text = "prix       :", back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 1, y = 9, text = "dispo      :", back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 1, y = 10, text = "type       :", back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 1, y = 11, text = "livraison  :", back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 1, y = 12, text = "adresse    :", back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 1, y = 13, text = "descrption :", back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 1, y = 14, text = "dateupdate :", back_color = 32768, text_color = 1})

    table.insert(global_term_objet_write,{x = 14, y = 5, text = global_liste_offre[0][global_variable["num_champ"]], back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 14, y = 6, text = global_liste_offre[2][global_variable["num_champ"]], back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 14, y = 7, text = global_liste_offre[7][global_variable["num_champ"]], back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 14, y = 8, text = global_liste_offre[3][global_variable["num_champ"]], back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 14, y = 9, text = global_liste_offre[4][global_variable["num_champ"]], back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 14, y = 10, text = global_http_error_message["type"][global_liste_offre[5][global_variable["num_champ"]]], back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 14, y = 11, text = global_http_error_message["livraison"][global_liste_offre[6][global_variable["num_champ"]]], back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 14, y = 12, text = global_liste_offre[1][global_variable["num_champ"]]["nom"], back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 14, y = 13, text = global_liste_offre[8][global_variable["num_champ"]], back_color = 32768, text_color = 1})
    table.insert(global_term_objet_write,{x = 14, y = 14, text = global_liste_offre[9][global_variable["num_champ"]], back_color = 32768, text_color = 1})
end